### ISSUE TITLE
Add element group colors

### ISSUE THREAD

**Issue by IvanIsak2000** [mb6ockatf/IVPT#23]
I really liked your repository, I did not expect that such a valuable application would come across to me, which I can use in chemistry lessons!
I suggest creating groups of colors and coloring elements depending on the group

![image](https://user-images.githubusercontent.com/79650307/229198170-b1a69c43-d519-4c67-bcef-155209a2cde3.png)

For example 
![image](https://user-images.githubusercontent.com/79650307/229198785-e69e696a-29fc-4546-9880-6d24ec64ccbb.png)

**Comment by mb6ockatf** [comment]
@IvanIsak2000 good idea. i am glad you liked the program)
unfortunately, i am quite really busy right now, so i will only be able to implement this feature in a couple of weeks or even more - quite a time; i am sorry for this

**Comment by mb6ockatf** [comment]
@IvanIsak2000 try it))
